services:
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=
      - MONGODB_INITDB_ROOT_PASSWORD=
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
